[package]
name = "qformat"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fkernel = { path = "../fkernel" }
qparse = { path = "../qparse" }
tracing = "0.1"
