[package]
name = "fcommon"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = { version = "0.1.5", optional = true }
salsa = "0.16.1"
tracing = "0.1.37"
upcast = "0.1.0"

[features]
