(module
  ()
  (def K_combinator (u)
    (pi A imp (sort (univvar u))
      (pi B imp (sort (univvar u))
        (pi x ex (bound 1)
          (pi x ex (bound 1)
            (bound 3))
    )))
    (lam A imp (sort (univvar u))
      (lam B imp (sort (univvar u))
        (lam x ex (bound 1)
          (lam x ex (bound 1)
            (bound 1))
    )))
  )
  (def I_combinator_from_K (u)
    (pi T imp (sort (univvar u))
      (pi x ex (bound 0)
        (bound 1)))
    (lam T imp (sort (univvar u))
      (lam x ex (bound 0)
        (ap (ap (ap (ap
          (inst (delta K_combinator) ((univvar u)))
          (bound 1))
          (bound 1))
          (bound 0))
          (bound 0))
    ))
  )
)
