(module ()
  (ind Prod () (u v)
    (pi A ex (sort (univsucc (univvar u)))
      (pi B ex (sort (univsucc (univvar u)))
        (sort (univsucc (univmax (univvar u) (univvar v))))))
    2 (
    (Prod.mk (pi A imp (sort (univsucc (univvar u)))
      (pi B imp (sort (univsucc (univvar u)))
        (pi fst ex (bound 1)
          (pi snd ex (bound 1)
            (ap (ap (inst (products_coproducts Prod) ((univvar u) (univvar v)))
              (bound 3))
              (bound 2))
      )))))
  ))
  (ind PProd () (u v)
    (pi A ex (sort (univvar u))
      (pi B ex (sort (univvar u))
        (sort (univmax (univsucc (univzero)) (univmax (univvar u) (univvar v))))))
    2 (
    (PProd.mk (pi A imp (sort (univvar u))
      (pi B imp (sort (univvar u))
        (pi fst ex (bound 1)
          (pi snd ex (bound 1)
            (ap (ap (inst (products_coproducts PProd) ((univvar u) (univvar v)))
              (bound 3))
              (bound 2))
      )))))
  ))
  (ind And () ()
    (pi A ex (sort (univzero))
      (pi B ex (sort (univzero))
        (sort (univzero))))
    2 (
    (And.mk (pi A imp (sort (univzero))
      (pi B imp (sort (univzero))
        (pi left ex (bound 1)
          (pi right ex (bound 1)
            (ap (ap (inst (products_coproducts And) ())
              (bound 3))
              (bound 2))
      )))))
  ))
  (ind Sum () (u v)
    (pi A ex (sort (univsucc (univvar u)))
      (pi B ex (sort (univsucc (univvar u)))
        (sort (univsucc (univmax (univvar u) (univvar v))))))
    2 (
    (Sum.inl (pi A imp (sort (univsucc (univvar u)))
      (pi B imp (sort (univsucc (univvar u)))
        (pi a ex (bound 1)
          (ap (ap (inst (products_coproducts Sum) ((univvar u) (univvar v)))
            (bound 2))
            (bound 1))
      ))))
    (Sum.inr (pi A imp (sort (univsucc (univvar u)))
      (pi B imp (sort (univsucc (univvar u)))
        (pi b ex (bound 0)
          (ap (ap (inst (products_coproducts Sum) ((univvar u) (univvar v)))
            (bound 2))
            (bound 1))
      ))))
  ))
  (ind PSum () (u v)
    (pi A ex (sort (univvar u))
      (pi B ex (sort (univvar u))
        (sort (univmax (univsucc (univzero)) (univmax (univvar u) (univvar v))))))
    2 (
    (PSum.inl (pi A imp (sort (univvar u))
      (pi B imp (sort (univvar u))
        (pi a ex (bound 1)
          (ap (ap (inst (products_coproducts PSum) ((univvar u) (univvar v)))
            (bound 2))
            (bound 1))
      ))))
    (PSum.inr (pi A imp (sort (univvar u))
      (pi B imp (sort (univvar u))
        (pi b ex (bound 0)
          (ap (ap (inst (products_coproducts PSum) ((univvar u) (univvar v)))
            (bound 2))
            (bound 1))
      ))))
  ))
  (ind Or () ()
    (pi A ex (sort (univzero))
      (pi B ex (sort (univzero))
        (sort (univzero))))
    2 (
    (Or.inl (pi A imp (sort (univzero))
      (pi B imp (sort (univzero))
        (pi a ex (bound 1)
          (ap (ap (inst (products_coproducts Or) ())
            (bound 2))
            (bound 1))
      ))))
    (Or.inr (pi A imp (sort (univzero))
      (pi B imp (sort (univzero))
        (pi b ex (bound 0)
          (ap (ap (inst (products_coproducts Or) ())
            (bound 2))
            (bound 1))
      ))))
  ))
  (ind Sigma () (u v)
    (pi A imp (sort (univsucc (univvar u)))
      (pi B ex (pi a ex (bound 0) (sort (univsucc (univvar v))))
        (sort (univmax (univsucc (univvar u)) (univsucc (univvar v))))))
    2 (
    (Sigma.mk (pi A imp (sort (univsucc (univvar u)))
      (pi B ex (pi a ex (bound 0) (sort (univsucc (univvar v))))
        (pi fst ex (bound 1)
          (pi snd ex (ap (bound 1) (bound 0))
            (ap (ap (inst (products_coproducts Sigma) ((univvar u) (univvar v)))
              (bound 3))
              (bound 2))
      )))
    ))
  ))
  (ind PSigma () (u v)
    (pi A imp (sort (univvar u))
      (pi B ex (pi a ex (bound 0) (sort (univvar v)))
        (sort (univmax (univsucc (univzero)) (univmax (univvar u) (univvar v))))))
    2 (
    (PSigma.mk (pi A imp (sort (univvar u))
      (pi B ex (pi a ex (bound 0) (sort (univvar v)))
        (pi fst ex (bound 1)
          (pi snd ex (ap (bound 1) (bound 0))
            (ap (ap (inst (products_coproducts PSigma) ((univvar u) (univvar v)))
              (bound 3))
              (bound 2))
      )))
    ))
  ))
  (ind Bool () ()
    (sort (univsucc (univzero)))
    0 (
    (false (inst (products_coproducts Bool) ()))
    (true (inst (products_coproducts Bool) ()))
  ))
)
