(module
  ()
  (def S_combinator (u)
    (pi A imp (sort (univvar u))
      (pi B imp (sort (univvar u))
        (pi C imp (sort (univvar u))
          (pi x ex (pi a ex (bound 2) (pi b ex (bound 2) (bound 2)))
            (pi y ex (pi a ex (bound 3) (bound 3))
              (pi z ex (bound 4)
                (bound 3)
          )))
    )))
    (lam A imp (sort (univvar u))
      (lam B imp (sort (univvar u))
        (lam C imp (sort (univvar u))
          (lam x ex (pi a ex (bound 2) (pi b ex (bound 2) (bound 2)))
            (lam y ex (pi a ex (bound 3) (bound 3))
              (lam z ex (bound 4)
                (ap (ap (bound 2) (bound 0)) (ap (bound 1) (bound 0)))
          )))
    )))
  )
  (def K_combinator (u)
    (pi A imp (sort (univvar u))
      (pi B imp (sort (univvar u))
        (pi x ex (bound 1)
          (pi x ex (bound 1)
            (bound 3))
    )))
    (lam A imp (sort (univvar u))
      (lam B imp (sort (univvar u))
        (lam x ex (bound 1)
          (lam x ex (bound 1)
            (bound 1))
    )))
  )
  (def I_combinator (u)
    (pi T imp (sort (univvar u))
      (pi x ex (bound 0)
        (bound 1)))
    (lam T imp (sort (univvar u))
      (lam x ex (bound 0)
        (bound 0)))
  )
)
